### ISSUE TITLE
Why does xorriso need root priviliges?

### ISSUE THREAD

**Issue by gapan** [gapan/iso-creation#8]
In 99-createiso.sh, it seems that xorriso needs root priviliges to create the iso. That shouldn't be so. A regular user should be able to create the iso with no problems. Maybe a file that xorrise uses belongs to root and is not readable by the user?

**Comment by gapan** [comment]
Fixed with 014d2d8d9b4f05dff7dbb435645eaf9049355674

**Comment by DidierSpaier** [comment]
According to my last test it doesn't and you could close this issue.
